config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'products#index'
  get '/products', to: 'products#index'
  get '/products/new', to: 'products#new', as: 'new_product'
  get '/products/:id', to: 'products#show'
  post '/products', to: 'products#create', as: 'create_product'
  delete '/products/:id', to: 'products#destroy', as: 'delete_product'
  get 'products/:id/edit', to: 'products#edit', as: 'edit_product'
  patch 'products/:id', to: 'products#update', as: 'update_product'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        response = HTTParty.get('http://localhost:3000/products.json')
        @products = JSON.parse(response.body)
      end
    
      def show
        id = params[:id]
        response = HTTParty.get("http://localhost:3000/products/#{id}.json")
        @product = JSON.parse(response.body)
      end

      def destroy
        url = "http://localhost:3000/products/#{params[:id]}"
        response = HTTParty.delete(url)
      
        if response.code == 204
          redirect_to products_path, notice: 'Product deleted successfully.'
        else
          redirect_to products_path, alert: 'Failed to delete product.'
        end
    end

    def new
      @product = {}
    end
    

    def create
      product_params = {
        name: params[:product][:name],
        price: params[:product][:price]
      }
      if product_params[:name].blank? || product_params[:price].blank?
        flash.now[:error] = 'Name and Price are required fields.'
        render :new
      else
        response = HTTParty.post("http://localhost:3000/products.json", body: { product: product_params })

      if response.success?
        flash[:success] = 'Product created successfully'
        redirect_to products_path
      else
        flash.now[:error] = 'Failed to create product'
        render :new
      end
    end
    end    

    def edit
      id = params[:id]
      response = HTTParty.get("http://localhost:3000/products/#{id}.json")
      if response.success?
        @product = JSON.parse(response.body)
      else
        flash.now[:error] = 'Failed to fetch product'
        redirect_to products_path
      end
    rescue StandardError
      flash.now[:error] = 'An error occurred while fetching the product'
      redirect_to products_path    
    end
    

    def update
      id = params[:id]
      product_params = {
        name: params[:product][:name],
        price: params[:product][:price]
      }
      response = HTTParty.patch("http://localhost:3000/products/#{id}.json", body: { product: product_params })
      puts response
      if response.success?
        flash[:success] = 'Product updated successfully'
        redirect_to products_path
      else
        flash.now[:error] = 'Failed to update product'
        render :edit
      end
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiConsumer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'rails-ujs' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> %>
  </head>

  <body>
    <!-- Flash messages -->
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>">
        <%= value %>
      </div>
    <% end %>

    <!-- Your body content -->
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<form action="<%= update_product_path(@product['id']) %>" method="post" id="edit-product-form">
  <%= hidden_field_tag '_method', 'patch' %>
  <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
  
  <div>
    <label for="product_name">Name</label>
    <input type="text" id="product_name" name="product[name]" value="<%= @product['name'] %>">
  </div>

  <div>
    <label for="product_price">Price</label>
    <input type="number" id="product_price" name="product[price]" value="<%= @product['price'] %>">
  </div>

  <div>
    <input type="submit" value="Update">
  </div>
</form>
<%= link_to 'Back', products_path, class: 'btn btn-primary' %>

app/views/products/index.html.erb
<h1> Create Product </h1>
<%= link_to 'Create Product', new_product_path, class: 'btn btn-primary' %>
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product['name'] %></td>
        <td><%= product['price'] %></td>
        <td>
          <%= link_to 'View', "/products/#{product['id']}", class: 'btn btn-primary' %>
          <%= link_to 'Delete', delete_product_path(product['id']), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          <%= link_to 'Edit', edit_product_path(product['id']), class: 'btn btn-secondary' %>
          <%# <%= link_to 'Edit', edit_product_path(product['id']), class: 'btn btn-secondary' %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<form action="<%= products_path %>" method="post" id="new-product-form">
  <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>

  <div>
    <label for="product_name">Name</label>
    <input type="text" id="product_name" name="product[name]">
  </div>

  <div>
    <label for="product_price">Price</label>
    <input type="number" id="product_price" name="product[price]">
  </div>

  <div>
    <input type="submit" value="Create Product">
  </div>
</form>
<%= link_to 'Back', products_path, class: 'btn btn-primary' %>

app/views/products/show.html.erb
<h1>Product</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @product['name'] %></td>
      <td><%= @product['price'] %></td>
       <td> <%= link_to 'Delete', delete_product_path(@product['id']), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %> </td>
      <td> <%= link_to 'Edit', edit_product_path(@product['id']), class: 'btn btn-secondary' %> </td>
    </tr>
    <tr>
    <td>
    <%= link_to 'Back', products_path, class: 'btn btn-primary' %>
    </td>
    </tr>
  </tbody>
</table>